vim.opt.mouse = ""
vim.opt.clipboard = "unnamedplus"

vim.opt.confirm = false
vim.opt.conceallevel = 0

vim.opt.shiftwidth = 2
vim.opt.softtabstop = 2
vim.opt.expandtab = true
vim.opt.autoindent = true
vim.opt.smartindent = true

vim.opt.smartcase = true

vim.opt.spelllang = "en"
vim.opt.spellfile = "$HOME/.config/nvim/spell/en.utf-8.add"
