"global settings
set title
"set shiftwidth=2
"set softtabstop=2
"set expandtab
"set copyindent
"set preserveindent
"set smarttab
"set autoindent
set smartindent
"set cindent
"set cinoptions=(0,u0,U0
set incsearch
set hlsearch
set showmatch
set wildmenu
set wildignore=*.o,*~,*.pyc,*.lo
set spelllang=en
set spellfile=$HOME/.vim/spell/en.utf-8.add
filetype plugin indent on
syntax on

"airline
set noshowmode
set laststatus=2
set t_Co=256
set guifont=Monospace\ Regular\ for\ Powerline\ 10
let g:airline_powerline_fonts=1

"themes and appearance
let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
if (has("termguicolors"))
  set termguicolors
endif
if filereadable( expand("$HOME/.vim/colors/colorific.vim") )
  let g:colorific_style='dark2'
  colorscheme colorific
  if filereadable( expand("$HOME/.vim/autoload/airline/themes/colorific.vim") )
    let g:airline_theme='colorific'
  endif
endif
set background=dark

"encryption
set cm=blowfish

"pathogen
"execute pathogen#infect()

"detectindent
:autocmd BufReadPost * :DetectIndent

"markdown/tex/text
au FileType bib,markdown,mkd,rmd,Rmd,tex,text,textile setlocal spell

"vim-taglist
let Tlist_Compact_Format = 1
let Tlist_GainFocus_On_ToggleOpen = 1
let Tlist_Close_On_Select = 1
nnoremap <C-l> :TlistToggle<CR>

"minibufexpl
let g:miniBufExplAutoStart=0
let g:miniBufExplHideWhenDiff=0

"nerd-commenter
let g:NERDSpaceDelims=1
"let g:NERDCompactSexyComs=1
let g:NERDDefaultAlign='left'
let g:NERDCommentEmptyLines=1

"youcompleteme
let g:ycm_extra_conf_globlist=['~/.ycm_extra_conf.py']

"clang-format
if filereadable( expand("/usr/share/vim/addons/syntax/clang-format.py") )
  map <C-K> :py3f /usr/share/vim/addons/syntax/clang-format.py<cr>
  imap <C-K> <c-o>:py3f /usr/share/vim/addons/syntax/clang-format.py<cr>
endif
