source /usr/share/zsh-antigen/antigen.zsh

antigen use oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-history-substring-search
antigen theme fishy
antigen apply

eval $(dircolors -b)

# enable color support of ls and also add handy aliases
alias ls='ls --color=auto'
alias sl='ls -r'
alias grep='grep --color=auto'
alias happymake="make -j`nproc` && sudo make install"
alias superupgrade="apt update && apt upgrade && apt dist-upgrade && apt autoremove && apt autoclean && update-grub"

# zsh fixes
alias scp="noglob scp"

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
