#! /bin/bash

# Debian (post-)install scripts
# Copyright (C) 2020
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


dir="$(dirname "$0")"
deps="${dir}/packages/deps.list"
install="${dir}/packages/install.list"

export midbranch="\0342\0224\0234\0342\0224\0200\0342\0224\0200"
export endbranch="\0342\0224\0224\0342\0224\0200\0342\0224\0200"

# # Tricks vim-autointent into thinking the default indent is 1 space.
# export heirarchy="Main
#  ${midbranch} Base
#  ${midbranch} Miscellaneous
#  ${midbranch} Desktop environment
#  ${midbranch} Network tools
#  ${midbranch} Applications
#  ${midbranch} Themes
#  ${endbranch} Personalization"

function check_user {
  if [ ${EUID} -eq 0 ]; then
    show_error "Don't run this script as root. Exiting."
    exit 1
  fi
}

function check_root {
  if [ ${EUID} -eq 0 ]; then
    show_info "I am root."
  else
    show_error "I need to be root."
    exit 1
  fi
}

function check_fail {
  local exitstatus=${1:-}
  if [[ ${exitstatus} -gt 0 ]]; then
    show_error "Error code received. Returning to main."
    sleep 3s && main
  fi
}

srclist="/etc/apt/sources.list"
function check_debian_release {
  show_header "Checking currently set Debian release."
  local release
  release=$(lsb_release -sc)
  if ! [[ "${release}" == "bookworm" ]] && \
     ! [[ "${release}" == "bullseye" ]] && \
     ! [[ "${release}" == "buster" ]] && \
     ! [[ "${release}" == "sid" ]]; then
    show_warning "Currently running ${release}"
    read -r -p $'\033[1;34mSwitch to bullseye (i.e. stable)? (y/N) \033[0m' response
    if [[ "${response}" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
      echo "Updating sources.list."
      sudo sed -i "/deb cdrom/d" ${srclist}
      sudo sed -i "/# *$/d" ${srclist}
      sudo sed -i "s/${release}/bullseye/g" ${srclist}
      sudo sh -c "apt-get update && \
        apt-get -y upgrade && \
        apt-get -y dist-upgrade \
        apt-get -y autoremove \
        apt-get -y autoclean \
        update-grub"
      show_info "Reboot your system after major updates."
    else
      show_warning "This script is not intended for $(lsb_release -sc)."
    fi
  else
    show_success "Now running ${release}."
  fi
}

function check_installed {
  while read -r package; do
    # Check if package is installed already before installing.
    if dpkg -s "${package}" >/dev/null 2>&1; then
      show_listitem "${package} package already installed. Skipping."
    else
      # First check if the package exists in the repos.
      if ! (apt-cache showsrc "${package}" 2>&1 | grep -q "W: "); then
        show_listitem "Installing ${package}."
        sudo apt-get -y install "${package}"
      else
        show_warning "Package ${package} does not exist in the repos. Skipping."
      fi
    fi
  done < "${1}"
}

function check_uninstalled {
  for package in "${@}"; do
    if dpkg -s "${package}" >/dev/null 2>&1; then
      show_listitem "Purging ${package}."
      sudo apt-get -y purge "${package}"
      sudo apt-get -y autoremove
    else
      show_warning "Package ${package} is not installed. Skipping."
    fi
  done
}

function install_post_dependencies {
  show_header "Checking post-installation dependencies."
  while read -r package; do
    if ! dpkg -s "${package}" > /dev/null 2>&1; then
      show_info "${package} is needed for this script."
      sudo apt-get -y install "${package}"
      check_fail $?
      show_success "${package} now installed."
    else
      show_success "${package} is already installed."
    fi
  done < "${deps}"
}

function install_dependencies {
  show_header "Checking installation dependencies."
  while read -r package; do
    if ! dpkg -s "${package}" > /dev/null 2>&1; then
      show_info "${package} is needed for this script."
      sudo apt-get -y install "${package}"
      check_fail $?
      show_success "${package} now installed."
    else
      show_success "${package} is already installed."
    fi
  done < "${install}"
}

function install_sudo {
  if ! dpkg -s sudo > /dev/null 2>&1; then
    show_header "sudo is needed for this script."
    show_info "Installing sudo via root (enter root password):"
    if [ ${EUID} -eq 0 ]; then
      apt-get -y install sudo
      show_success "sudo installed." # will exit after check_user()
    else
      su root - sh -c "apt-get -y install sudo && /sbin/adduser $(whoami) sudo"
      show_success "sudo installed and $(whoami) added to group sudo."
      show_info "Log out and log back in again."
      exit
    fi
  elif ! [[ $(groups) =~ \ *sudo\ * ]]; then
    show_error "User $(whoami) not in sudoer group."
    show_info "If the root user is enabled, run:"
    show_listitem "su root - sh -c \"/sbin/adduser $(whoami) sudo\""
    show_info "Then, log out and log back in again."
    exit
  fi
}

function check_network {
  show_header "Checking network connection."

  if wget -q --tries=10 --timeout=20 --spider https://debian.org >/dev/null; then
    show_success "Network is working."
  else
    show_error "Cannot start network connection."
    exit 1
  fi
}
