#! /bin/bash

# Debian (post-)install scripts
# Copyright (C) 2020
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

DIR="$(dirname "$0")"

function install_base {
  local base="${DIR}/packages/base.list"
  local bashrc="${DIR}/dotfiles/bashrc"
  local bashprofile="${DIR}/dotfiles/bash_profile"

  show_header "Installing base packages and their config files."
  check_installed "${base}"
  show_success "Base packages installed."

  copy_config_file "${bashprofile}" "${HOME}/.bash_profile"
  copy_config_file "${bashrc}" "${HOME}/.bashrc"
}

function install_firmware {
  local firmware="${DIR}/packages/firmware.list"
  local srclist="/etc/apt/sources.list"
  local release
  release=$(lsb_release -sc)
  if ! grep 'non-free\( \|$\)' "${srclist}" > /dev/null 2>&1; then
    show_warning "non-free repos need to be enabled first."
  else
    show_header "Installing non-free firmware."
    check_installed "${firmware}"
    show_success "Firmware installed."
  fi
}

function enable_contrib_repos {
  local srclist="/etc/apt/sources.list"
  local release
  release=$(lsb_release -sc)
  if ! grep contrib "${srclist}" > /dev/null 2>&1; then
    show_info "Enabling contrib repos."
    sudo sed -i \
      '/deb/{/ contrib\(\ \|$\)/! s/$/ contrib/}' "${srclist}"
    sync_repos
  else
    show_info "contrib already enabled."
  fi
}

function enable_nonfree-firmware_repos {
  local srclist="/etc/apt/sources.list"
  local release
  release=$(lsb_release -sc)
  if ! grep non-free-firmware "${srclist}" > /dev/null 2>&1; then
    show_info "Enabling non-free-firmware repos."
    sudo sed -i \
      '/deb/{/ non-free-firmware\(\ \|$\)/! s/$/ non-free-firmware/}' "${srclist}"
    sync_repos
  else
    show_info "non-free-firmware already enabled."
  fi
}

function enable_nonfree_repos {
  local srclist="/etc/apt/sources.list"
  local release
  release=$(lsb_release -sc)
  if ! grep 'non-free\( \|$\)' "${srclist}" > /dev/null 2>&1; then
    show_info "Enabling non-free repos."
    sudo sed -i \
      '/deb/{/ non-free\(\ \|$\)/! s/$/ non-free/}' "${srclist}"
    sync_repos
  else
    show_info "non-free already enabled."
  fi
}

function upgrade_debian_release {
  local srclist="/etc/apt/sources.list"
  local busterlist="${DIR}/sources/buster-sources.list"
  local bullseyelist="${DIR}/sources/bullseye-sources.list"
  local bookwormlist="${DIR}/sources/bookworm-sources.list"
  local trixielist="${DIR}/sources/trixie-sources.list"
  local sidlist="${DIR}/sources/sid-sources.list"

  # check how current sources.list is configured.
  local is_onion=false
  local is_contrib=false
  local is_nonfree=false
  local is_nonfreefirmware=false
  if grep -q onion "${srclist}"; then
    is_onion=true
  fi
  if grep -q contrib "${srclist}"; then
    is_contrib=true
  fi
  if grep -q 'non-free\( \|$\)' "${srclist}"; then
    is_nonfree=true
  fi
  if grep -q non-free-firmware "${srclist}"; then
    is_nonfreefirmware=true
  fi

  local is_upgraded=false
  local release
  release="$(lsb_release -sc)"

  show_question "Upgrade Debian release?"
  local options=("Back" "Buster" "Bullseye" "Bookworm" "Trixie" "Sid")
  local option
  select option in "${options[@]}"; do
    case "${option}" in
      "Back")
        break
        ;;
      "Buster")
        if [[ "${release}" == "buster" ]]; then
          show_warning "Already set to ${release}."
        elif [[ "${release}" == "bullseye" ]] ||
             [[ "${release}" == "bookworm" ]] ||
             [[ "${release}" == "trixie" ]] ||
             [[ "${release}" == "sid" ]]; then
          show_warning "Downgrades not possible."
        else
          sudo cp -f "${srclist}" "${srclist}.${RANDOM}.bak"
          sudo cp -f "${busterlist}" "${srclist}"
          is_upgraded=true
          release=buster
        fi
        break
        ;;
      "Bullseye")
        if [[ "${release}" == "bullseye" ]]; then
          show_warning "Already set to ${release}."
        elif [[ "${release}" == "bookworm" ]] ||
             [[ "${release}" == "trixie" ]] ||
             [[ "${release}" == "sid" ]]; then
          show_warning "Downgrades not possible."
        else
          sudo cp -f "${srclist}" "${srclist}.${RANDOM}.bak"
          sudo cp -f "${bullseyelist}" "${srclist}"
          is_upgraded=true
          release=bullseye
        fi
        break
        ;;
      "Bookworm")
        if [[ "${release}" == "bookworm" ]]; then
          show_warning "Already set to ${release}."
        elif [[ "${release}" == "trixie" ]] ||
             [[ "${release}" == "sid" ]]; then
          show_warning "Downgrades not possible."
        else
          if [[ "${release}" == "buster" ]] ||
             [[ "${release}" == "bullseye" ]]; then
            if [[ "${is_nonfree}" == true ]]; then
              is_nonfreefirmware=true
            fi
          fi
          sudo cp -f "${srclist}" "${srclist}.${RANDOM}.bak"
          sudo cp -f "${bookwormlist}" "${srclist}"
          is_upgraded=true
          release=bookworm
        fi
        break
        ;;
      "Trixie")
        if [[ "${release}" == "trixie" ]]; then
          show_warning "Already set to ${release}."
        elif [[ "${release}" == "sid" ]]; then
          show_warning "Downgrades not possible."
        else
          if [[ "${release}" == "buster" ]] ||
             [[ "${release}" == "bullseye" ]]; then
            if [[ "${is_nonfree}" == true ]]; then
              is_nonfreefirmware=true
            fi
          fi
          sudo cp -f "${srclist}" "${srclist}.${RANDOM}.bak"
          sudo cp -f "${trixielist}" "${srclist}"
          is_upgraded=true
          release=trixie
        fi
        break
        ;;
      "Sid")
        if [[ "${release}" == "sid" ]]; then
          show_warning "Already set to ${release}."
        else
          if [[ "${release}" == "buster" ]] ||
             [[ "${release}" == "bullseye" ]]; then
            if [[ "${is_nonfree}" == true ]]; then
              is_nonfreefirmware=true
            fi
          fi
          sudo cp -f "${srclist}" "${srclist}.${RANDOM}.bak"
          sudo cp -f "${sidlist}" "${srclist}"
          is_upgraded=true
          release=sid
        fi
        break
        ;;
      *)
        show_warning "Invalid option."
        show_info "Hit ENTER to see options again."
        ;;
    esac
  done

  if [ "${is_upgraded}" == true ]; then
    if [ "${is_contrib}" == true ]; then
      sudo sed -i \
        '/deb/{/ contrib\(\ \|$\)/! s/$/ contrib/}' "${srclist}"
    fi
    if [ "${is_nonfree}" == true ]; then
      sudo sed -i \
        '/deb/{/ non-free\(\ \|$\)/! s/$/ non-free/}' "${srclist}"
    fi
    if [ "${is_nonfreefirmware}" == true ]; then
      sudo sed -i \
        '/deb/{/ non-free-firmware\(\ \|$\)/! s/$/ non-free-firmware/}' "${srclist}"
    fi
    if [ "${is_onion}" == true ]; then
      sudo sed -i \
        -e "s,https://deb.debian.org,tor+http://vwakviie2ienjx6t.onion,g" \
        -e "s,https://security.debian.org/,tor+http://sgvtcaew4bxjd7ln.onion/debian-security/,g" ${srclist}
    fi

    sync_repos
    sudo sh -c "apt-get -y upgrade && \
                apt-get -y dist-upgrade && \
                apt-get -y autoremove && \
                apt-get -y autoclean && \
                update-grub"

    show_info "Reboot your system after major updates."
  fi
}

function enable_sudo_insults {
  # Customize sudo to insult incorrect password attempts
  if ! sudo grep "^Defaults\s\+insults" /etc/sudoers > /dev/null 2>&1; then
    show_info "Enabling sudo insults."
    sudo sh -c 'cat /etc/sudoers | \
                sed -e "/^Defaults\tsecure_path/a Defaults\tinsults" | \
                (EDITOR="tee" visudo >/dev/null)'
  else
    show_info "Insults already enabled, you masochist."
  fi
}

function purge_packages {
  local purge="${DIR}/packages/purge.list"
  show_header "Purging unwanted packaged often installed by default."
  check_uninstalled "${purge}"
  show_success "Unwanted packages purged."
}

function update_packages {
  show_header "Updating packages."
  sync_repos
  sudo sh -c "apt-get -y upgrade && \
              apt-get -y dist-upgrade && \
              apt-get -y autoremove && \
              apt-get -y autoclean && \
              update-grub"
  show_success "Packages updated."
}

function disable_beep {
  local pcspkr_blacklist="/etc/modprobe.d/nobeep.conf"
  local gtk2conf="${HOME}/.gtkrc-2.0"
  local gtk3conf="${HOME}/.config/gtk-3.0/settings.ini"

  show_header "Disable PC speaker beep."
  show_info "Blacklisting pcspkr and snd_pcsp kernel modules."
  if ! [ "$(ls -A /etc/modprobe.d/)" ]; then
    sudo sh -c "echo 'blacklist pcspkr' >> ${pcspkr_blacklist}"
    sudo sh -c "echo 'blacklist snd_pcsp' >> ${pcspkr_blacklist}"
  else
    if ! find /etc/modprobe.d/ -type f \
         -exec grep "blacklist pcspkr" {} + > /dev/null 2>&1; then
      sudo sh -c "echo 'blacklist pcspkr' >> ${pcspkr_blacklist}"
    fi
    if ! find /etc/modprobe.d/ -type f \
         -exec grep "blacklist snd_pcsp" {} + > /dev/null 2>&1; then
      sudo sh -c "echo 'blacklist snd_pcsp' >> ${pcspkr_blacklist}"
    fi
  fi
  show_success "Blacklisted in ${pcspkr_blacklist@Q}."

  show_info "Disabling gtk2 and gtk3 error-bell."
  if [ -f "${gtk2conf}" ]; then
    if grep "^gtk-error-bell=" "${gtk2conf}" > /dev/null 2>&1; then
      sed -i "s/^gtk-error-bell=.*$/gtk-error-bell=0/g" "${gtk2conf}"
    else
      echo "gtk-error-bell=0" >> "${gtk2conf}"
    fi
  else
    mkdir -p "$(dirname "${gtk2conf}")"
    echo "gtk-error-bell=0" >> "${gtk2conf}"
  fi
  if [ -f "${gtk3conf}" ]; then
    if grep "^gtk-error-bell=" "${gtk3conf}" > /dev/null 2>&1; then
      sed -i "s/^gtk-error-bell=.*$/gtk-error-bell=0/g" "${gtk3conf}"
    elif grep "^[Settings]" "${gtk3conf}" > /dev/null 2>&1; then
      sed -i "/^[Settings]$/a gtk-error-bell=0" "${gtk3conf}"
    else
      echo "[Settings]" >> "${gtk3conf}"
      echo "gtk-error-bell=0" >> "${gtk3conf}"
    fi
  else
    mkdir -p "$(dirname "${gtk3conf}")"
    echo "[Settings]" > "${gtk3conf}"
    echo "gtk-error-bell=0" >> "${gtk3conf}"
  fi
}

function 01-base {
  show_question "Base: what do you want to install?"
  show_info "Main\n ${ENDBRANCH} Base (Hit ENTER to see options again.)"

  local options=(
    "Back"
    "All"
    "Base packages"
    "Purge packages"
    "Firmware"
    "Updates"
    "Enable contrib"
    "Enable non-free"
    "Enable non-free-firmware"
    "Upgrade Debian release"
    "Sudo insults"
    "Disable system beep")
  local option
  select option in "${options[@]}"; do
    case "${option}" in
      "Back")
        break
        ;;
      "All")
        purge_packages
        update_packages
        install_base
        install_firmware
        enable_contrib_repos
        enable_nonfree_repos
        enable_nonfree-firmware_repos
        enable_sudo_insults
        disable_beep
        show_info "Main\n ${ENDBRANCH} Base (Hit ENTER to see options again.)"
        break
        ;;
      "Base packages")
        install_base
        show_info "Main\n ${ENDBRANCH} Base (Hit ENTER to see options again.)"
        ;;
      "Purge packages")
        purge_packages
        show_info "Main\n ${ENDBRANCH} Base (Hit ENTER to see options again.)"
        ;;
      "Firmware")
        install_firmware
        show_info "Main\n ${ENDBRANCH} Base (Hit ENTER to see options again.)"
        ;;
      "Updates")
        update_packages
        show_info "Main\n ${ENDBRANCH} Base (Hit ENTER to see options again.)"
        ;;
      "Enable contrib")
        enable_contrib_repos
        show_info "Main\n ${ENDBRANCH} Base (Hit ENTER to see options again.)"
        ;;
      "Enable non-free")
        enable_nonfree_repos
        show_info "Main\n ${ENDBRANCH} Base (Hit ENTER to see options again.)"
        ;;
      "Enable non-free-firmware")
        enable_nonfree-firmware_repos
        show_info "Main\n ${ENDBRANCH} Base (Hit ENTER to see options again.)"
        ;;
      "Upgrade Debian release")
        upgrade_debian_release
        show_info "Main\n ${ENDBRANCH} Base (Hit ENTER to see options again.)"
        ;;
      "Sudo insults")
        enable_sudo_insults
        show_info "Main\n ${ENDBRANCH} Base (Hit ENTER to see options again.)"
        ;;
      "Disable system beep")
        disable_beep
        show_info "Main\n ${ENDBRANCH} Base (Hit ENTER to see options again.)"
        ;;
      *)
        show_warning "Invalid option."
        show_info "Main\n ${ENDBRANCH} Base (Hit ENTER to see options again.)"
        ;;
    esac
  done
}
