#! /bin/bash
#set -eu

dir="$(dirname "$0")"

gnome="${dir}/packages/gnome.list"
function install_gnome {
  show_header "Setting up GNOME desktop environment."
  check_installed $(cat ${gnome})
  check_fail
  show_success "GNOME installed."
}

cinnamon="${dir}/packages/cinnamon.list"
function install_cinnamon {
  show_header "Setting up cinnamon desktop environment."
  check_installed $(cat ${cinnamon})
  check_fail
  show_success "Cinnamon installed."
}

function install_desktop {
  availabledesktops=("GNOME" "Cinnamon")
  show_question "Which desktop environment do you want?"
  select reply in "${availabledesktops[@]}"; do
    case $reply in
      "GNOME")
        show_info "$reply selected."
        install_gnome
        break
        ;;
      "Cinnamon")
        show_info "$reply selected."
        install_cinnamon
        break
        ;;
      *)
        show_warning "Invalid option."
        break
        ;;
    esac
  done
}

function 02-desktop {
  install_desktop
}
