#! /bin/bash

# Debian (post-)install scripts
# Copyright (C) 2020
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


dir="$(dirname "$0")"

gnome="${dir}/packages/gnome.list"
function install_gnome {
  show_header "Setting up GNOME desktop environment."
  check_installed "${gnome}"
  check_fail
  show_success "GNOME installed."

  show_info "Putting things into place."
  if ! test ${DESKTOP_SESSION+x}; then
    export DESKTOP_SESSION="gnome"
  fi
  xdg-user-dirs-update

  extensiondir=${HOME}/.local/share/gnome-shell/extensions
  mkdir -p "${extensiondir}"
  show_info "Downloading 'Desktop Icons' GNOME extension."
  git clone https://gitlab.com/rastersoft/desktop-icons-ng \
    "${HOME}/.local/share/gnome-shell/extensions/ding@rastersoft.com"

  show_info "Done."
}

cinnamon="${dir}/packages/cinnamon.list"
lightdmconf="/etc/lightdm/lightdm.conf"
gammastepini="${dir}/configs/gammastep.ini"
function install_cinnamon {
  show_header "Setting up cinnamon desktop environment."
  check_installed "${cinnamon}"
  check_fail
  show_success "Cinnamon installed."

  show_info "Putting things into place."
  if ! test ${DESKTOP_SESSION+x}; then
    export DESKTOP_SESSION="cinnamon"
  fi

  # Get latitude and longitude using GeoClue2 for Redshift.
  if [ -e /usr/lib/geoclue-2.0/demos/where-am-i ]; then
    show_info "Generating Redshift config."
    mkdir -p "${HOME}/.config/"
    local tmp
    local lat
    local lon
    tmp="$(/usr/lib/geoclue-2.0/demos/where-am-i -t 10 -a 4)"
    if [[ -n "${tmp}" ]]; then
      lat="$(echo "$tmp" | \
             sed -n "s/^Latitude: \+\([-0-9\.]\+\)°$/\1/p" | head -n 1)"
      lon="$(echo "$tmp" | \
             sed -n "s/^Longitude: \+\([-0-9\.]\+\)°$/\1/p" | head -n 1)"
      sed -e "s,^lat=.*,lat=${lat},g" -e "s,^lon=.*,lon=${lon},g" \
        "${gammastepini}" > "${HOME}/.config/gammastep/gammastep.conf"
    else
      cp "${gammastepini}" "${HOME}/.config/gammastep/gammastep.conf"
    fi
  fi

  xdg-user-dirs-update

  show_info "Setting up LightDM greeter."
  sudo sed -i \
    "s/^#greeter-hide-users=false/greeter-hide-users=false/g" \
    "${lightdmconf}"
  show_info "Done."
}

function 02-desktop {
  show_question "Desktop: what do you want to install?"
  show_info "Main\n ${endbranch} Desktop (Hit ENTER to see options again.)"

  local options=("Back" "All" "GNOME" "Cinnamon")
  select option in "${options[@]}"; do
    case $option in
      "Back")
        break
        ;;
      "All")
        install_gnome
        install_cinnamon
        show_info "Main\n ${endbranch} Desktop (Hit ENTER to see options again.)"
        ;;
      "GNOME")
        install_gnome
        show_info "Main\n ${endbranch} Desktop (Hit ENTER to see options again.)"
        ;;
      "Cinnamon")
        install_cinnamon
        show_info "Main\n ${endbranch} Desktop (Hit ENTER to see options again.)"
        ;;
      *)
        show_warning "Invalid option."
        ;;
    esac
  done
}
