#! /bin/bash
#set -eu

dir="$(dirname "$0")"

networking="${dir}/packages/network.list"
nmconf="/etc/NetworkManager/NetworkManager.conf"
nsconf="/etc/nsswitch.conf"
function install_network {
  show_header "Setting up networking."
  check_installed $(cat ${networking})
  check_fail
  show_success "Networking applications installed."

  show_info "Setting up MAC address randomization in Network Manager."
  if ! test "$(grep "mac-address=random" ${nmconf})"; then
    sudo sh -c "echo "" >> ${nmconf}"
    sudo sh -c "echo '## Enabling built-in MAC Address randomization' >> ${nmconf}"
    sudo sh -c "echo "[connection]" >> ${nmconf}"
    sudo sh -c "echo "wifi.cloned-mac-address=random" >> ${nmconf}"
    sudo sh -c "echo "ethernet.cloned-mac-address=random" >> ${nmconf}"
    sudo systemctl restart NetworkManager
  fi

  show_info "Enabling ufw."
  sudo ufw enable
  sudo systemctl enable ufw.service

  show_info "Enabling and starting tor service."
  sudo systemctl enable tor
  sudo systemctl start tor
}

function 03-network {
  show_question "Network: what do you want to install?"
  show_info "Main\n ${endbranch} Network (Hit ENTER to see options again.)"

  options=("Back" "All" "Network tools")
  select option in "${options[@]}"; do
    case $option in
      "Back")
        break
        ;;
      "All")
        install_network
        show_info "Main\n ${endbranch} Network (Hit ENTER to see options again.)"
        ;;
      "Network tools")
        install_network
        show_info "Main\n ${endbranch} Network (Hit ENTER to see options again.)"
        ;;
      *)
        show_warning "Invalid option."
        ;;
    esac
  done
}
