#! /bin/bash

dir="$(dirname "$0")"

npmrc="${dir}/dotfiles/npmrc"
themes="${dir}/packages/themes.list"
function install_theme_deps {
  show_header "Installing theme dependencies."
  check_installed $(cat ${themes})
  check_fail
  show_success "Theme dependencies installed."

  if ! command -v gulp >/dev/null; then
    if ! [ -f ${HOME}/.npm/bin/gulp ]; then
      show_header "Locally installing gulp."
      cp -f ${npmrc} ${HOME}/.npmrc
      npm -g install gulp
    fi

    # The script runs in a bash shell, so the npm install directory and the
    # environment variables for npm binaries need to be set here manually.
    export PATH="$PATH:$HOME/.npm/bin"
    export NPM_CONFIG_PREFIX=$HOME/.npm
  fi
}

function install_arc_gtk {
  show_header "Downloading, building, and installing the Arc GTK theme."
  git clone -b tweak --depth 1 \
    https://github.com/sudorook/arc-theme arc-theme
  cd arc-theme
  npm install
  ./autogen.sh --prefix=/usr
  gulp
  make -j`nproc`
  sudo make install
  cd ..
  rm -rf arc-theme
}

function install_adapta_gtk {
  show_header "Downloading, building, and installing the Adapta GTK theme."
  autotools_options=""
  if ! dpkg -s gnome-shell > /dev/null 2>&1; then
    autotools_options=${autotools_options}"--disable-gnome "
  elif ! dpkg -s cinnamon > /dev/null 2>&1; then
    autotools_options=${autotools_options}"--disable-cinnamon "
  fi
  git clone -b tweak --depth 1 \
    https://github.com/sudorook/adapta-gtk-theme adapta-gtk-theme
  cd adapta-gtk-theme
  ./autogen.sh \
    --prefix=/usr \
    --with-selection_color=#00A2B4 \
    --with-accent_color=#00B4CB \
    --with-suggestion_color=#00A2B4 \
    --with-destruction_color=#F44336 \
    ${autotools_options} \
    --enable-parallel
  make -j`nproc`
  sudo make install
  if [ -d /usr/share/gtksourceview-3.0/styles/ ]; then
    sudo cp -f extra/gedit/adapta.xml /usr/share/gtksourceview-3.0/styles/
  fi
  if [ -d /usr/share/gtksourceview-2.0/styles/ ]; then
    sudo cp -f extra/gedit/adapta.xml /usr/share/gtksourceview-2.0/styles/
  fi
  cd ..
  rm -rf adapta-gtk-theme
}

fonts="${dir}/packages/fonts.list"
function install_fonts {
  show_header "Installing fonts."
  check_installed $(cat ${fonts})
  check_fail
  show_success "Fonts installed."
}

function install_papirus_icons {
  show_header "Downloading and installing the Papirus icon theme."
  git clone -b tweak --depth 1 https://github.com/sudorook/papirus-icon-theme \
    papirus-icon-theme
  cd papirus-icon-theme

  sudo make install
  cd ..
  rm -rf papirus-icon-theme
}

function install_vim_theme {
  git clone --depth 1 https://github.com/sudorook/colorific.vim colorific.vim
  cd colorific.vim
  ./install.sh
  cd ../
  rm -rf colorific.vim/
}

function install_thunderbird_theme {
  if ! [ -d ${HOME}/.thunderbird/*.default ]; then
    show_warning "Thunderbird profile missing. Skipping."
    return
  fi

  thunderbird="$(echo ~/.thunderbird/*.default)"
  show_header "Installing Monterail theme for Thunderbird."
  if [ -d ${thunderbird}/chrome ]; then
    show_info "${thunderbird}/chrome already exists. Backing up and replacing."
    mv ${thunderbird}/chrome ${thunderbird}/chrome.${RANDOM}.bak
  else
    mkdir -p ${thunderbird}/chrome
  fi

  git clone https://github.com/entercloudbr/chrome ${thunderbird}/chrome

  local userchrome=${thunderbird}/chrome/userChrome.css
  sed -i 's|^\s*\(--folder-tree-background-color: rgba(247,247,255,1);\)|/\*\1\*/|g' ${userchrome}
  sed -i 's|^\(\s*\)\(--folder-tree-background-color: rgba(247,247,255,1);\)|\1/\*\2\*/|g' ${userchrome}
  sed -i 's|^\(\s*\)\(--message-list-header-background-color: rgba(247,247,255,1);\)|\1/\*\2\*/|g' ${userchrome}
  sed -i 's|^\(\s*\)\(--message-list-background-color: white;\)|\1/\*\2\*/|g' ${userchrome}
  sed -i 's|^\(\s*\)\(--message-list-row-height: 60px;\)|\1/\*\2\*/|g' ${userchrome}
  sed -i 's|^\(\s*\)\(--subject-line-font-size: 150%;\)|\1/\*\2\*/|g' ${userchrome}
  sed -i 's|^\(\s*\)\(--headers-background-color: white;\)|\1/\*\2\*/|g' ${userchrome}
}

function install_timed_backgrounds {
  git clone --depth 1 https://github.com/sudorook/timed-backgrounds \
    timed-backgrounds
  cd timed-backgrounds
  ./autogen.sh
  make -j`nproc`
  sudo make install
  cd ../
  rm -rf timed-backgrounds/
}

qt5ctconf="${dir}/configs/qt5ct.conf"
function set_qtcompat {
  show_header "Building qt5-styleplugins."
  git clone https://github.com/mati75/qt5ct
  cd qt5ct
  git checkout f8f1ebe09351e7eb1ea97d38f4506fe2be0519c7
  qmake
  make -j`nproc`
  sudo make install
  cd ..
  rm -rf qt5ct

  show_info "Copying qt5ct config."
  mkdir -p ${HOME}/.config/qt5ct
  cp -f ${qt5ctconf} ${HOME}/.config/qt5ct
  export QT_QPA_PLATFORMTHEME=qt5ct
}

function 04-themes {
  show_question "Themes: what do you want to install?"
  show_info "Main\n ${endbranch} Themes (Hit ENTER to see options again.)"

  options=("Back" "All" "Arc (GTK)" "Adapta (GTK)" "Fonts" "Papirus (icons)" \
           "Vim theme" "Thunderbird theme" "Timed backgrounds")
  select option in "${options[@]}"; do
    case $option in
      "Back")
        break
        ;;
      "All")
        install_theme_deps
        install_arc_gtk
        install_adapta_gtk
        install_fonts
        install_papirus_icons
        install_vim_theme
        install_thunderbird_theme
        install_timed_backgrounds
        set_qtcompat
        show_info "Main\n ${endbranch} Themes (Hit ENTER to see options again.)"
        ;;
      "Arc (GTK)")
        show_info "Installing dependencies for building themes."
        install_theme_deps
        install_arc_gtk
        set_qtcompat
        show_info "Main\n ${endbranch} Themes (Hit ENTER to see options again.)"
        ;;
      "Adapta (GTK)")
        show_info "Installing dependencies for building themes."
        install_theme_deps
        install_adapta_gtk
        set_qtcompat
        show_info "Main\n ${endbranch} Themes (Hit ENTER to see options again.)"
        ;;
      "Fonts")
        install_fonts
        show_info "Main\n ${endbranch} Themes (Hit ENTER to see options again.)"
        ;;
      "Papirus (icons)")
        install_papirus_icons
        show_info "Main\n ${endbranch} Themes (Hit ENTER to see options again.)"
        ;;
      "Vim theme")
        install_vim_theme
        show_info "Main\n ${endbranch} Themes (Hit ENTER to see options again.)"
        ;;
      "Thunderbird theme")
        install_thunderbird_theme
        show_info "Main\n ${endbranch} Themes (Hit ENTER to see options again.)"
        ;;
      "Timed backgrounds")
        install_timed_backgrounds
        show_info "Main\n ${endbranch} Themes (Hit ENTER to see options again.)"
        ;;
      *)
        show_warning "Invalid option."
        ;;
    esac
  done
}
