#!/bin/bash

# SPDX-FileCopyrightText: 2017 - 2024 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -euo pipefail

DIR="$(dirname "$0")"

#
# Source the functions
#

. "${DIR}"/functions/00-check
. "${DIR}"/functions/01-base
. "${DIR}"/functions/01-misc
. "${DIR}"/functions/02-desktop
. "${DIR}"/functions/03-network
. "${DIR}"/functions/03-packages
. "${DIR}"/functions/04-themes
. "${DIR}"/functions/05-personal

#
# Define main select wrapper
#

function main {
  show_question "Select an option:"
  show_info "Main (Hit ENTER to see options again.)"
  local options=(
    "Quit"
    "Autopilot"
    "Base"
    "Miscellaneous"
    "Desktop environment"
    "Network tools"
    "Applications"
    "Themes"
    "Personalization")
  local option
  select option in "${options[@]}"; do
    case "${option}" in
      "Quit")
        show_success "I hope this was as fun for you as it was for me."
        break
        ;;
      "Autopilot")
        local response
        response=$(ask_question "Let this script install everything? (y/N)")
        if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
          # Install base packages
          # purge_packages
          # update_packages
          install_base
          install_firmware
          enable_contrib_repos
          enable_nonfree_repos
          enable_nonfree-firmware_repos
          enable_sudo_insults
          disable_beep

          # Install miscellaneous extras
          install_utils
          # install_laptop
          # install_plymouth
          install_selinux
          install_zsh

          # Install a desktop environment
          # install_gnome
          # install_cinnamon
          install_kde

          # Set up network configuration
          install_network
          # install_discovery
          install_firewall
          # install_tor
          # use_onion_repos

          # Install useful packages
          install_3d_accel
          # install_android
          # install_apps
          install_apps_kde
          install_codecs
          install_containers
          install_dev
          # install_nix
          # install_extra
          install_extra_kde
          # install_pipewire
          # install_printing
          # install_games
          # install_kvm
          # install_kvm_guest
          install_messaging
          # install_mingw
          install_music
          install_texlive
          # install_torbrowser
          # install_vim
          # install_neovim
          install_lazyvim
          # install_virtualbox
          # install_virtualbox_guest
          # install_wine

          # Install themes
          # install_theme_deps_gtk
          # install_theme_deps_kde
          # install_arc_gtk
          # install_arc_kde
          # install_adapta_gtk
          # install_plata_gtk
          # install_materia_gtk
          # install_materia_kde
          install_fonts
          # install_papirus_icons
          # install_colorific_themes
          install_nightfox_themes
          # install_timed_backgrounds
          install_plasma_timed_backgrounds
          # set_qtcompat

          # Add my personal settings
          set_system_font
          # set_icon_theme
          # set_gtk_theme
          set_plasma_theme
          # set_lightdm_theme
          # set_gdm_theme
          set_sddm_theme
          # set_dark_gtk
          # set_bash_shell
          set_zsh_shell
          # import_cinnamon_dconf
          # import_gnome_dconf
          import_kde_settings
          # import_apps_dconf
          # import_terminal_dconf
          enable_autologin
          # invert_brightness
          # enable_intel_iommu
          # disable_pulseaudio_suspend
          disable_11n
          install_scripts

          show_success "Everything installed."
        fi

        show_info "Main (Hit ENTER to see options again.)"
        ;;
      "Base")
        01-base
        show_info "Main (Hit ENTER to see options again.)"
        ;;
      "Miscellaneous")
        01-misc
        show_info "Main (Hit ENTER to see options again.)"
        ;;
      "Desktop environment")
        02-desktop
        show_info "Main (Hit ENTER to see options again.)"
        ;;
      "Network tools")
        03-network
        show_info "Main (Hit ENTER to see options again.)"
        ;;
      "Applications")
        03-packages
        show_info "Main (Hit ENTER to see options again.)"
        ;;
      "Themes")
        04-themes
        show_info "Main (Hit ENTER to see options again.)"
        ;;
      "Personalization")
        05-personal
        show_info "Main (Hit ENTER to see options again.)"
        ;;
      *)
        show_warning "Invalid option."
        ;;
    esac
  done
}

#
# Check if dependencies are installed and if network is working
#

check_user
check_debian_release
check_network
install_sudo
check_sync_repos
install_post_dependencies

#
# GO!!!
#

main
