#! /bin/bash
set -euo pipefail

# Debian (post-)install scripts
# Copyright (C) 2020
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


dir="$(dirname "$0")"


#
# Fancy color output
#

show_error() {
  echo -e $'\033[1;31m'"$*"$'\033[0m' 1>&2
}
show_info() {
  echo -e $'\033[1;32m'"$*"$'\033[0m'
}
show_warning() {
  echo -e $'\033[1;33m'"$*"$'\033[0m'
}
show_question() {
  echo -e $'\033[1;34m'"$*"$'\033[0m'
}
ask_question() {
  read -r -p $'\033[1;34m'"$* "$'\033[0m' var
  echo "${var}"
}
show_success() {
  echo -e $'\033[1;35m'"$*"$'\033[0m'
}
show_header() {
  echo -e $'\033[1;36m'"$*"$'\033[0m'
}
show_listitem() {
  echo -e $'\033[1;37m'"$*"$'\033[0m'
}

export -f show_error
export -f show_info
export -f show_warning
export -f show_question
export -f ask_question
export -f show_success
export -f show_header
export -f show_listitem


#
# Source the functions
#

. "${dir}"/functions/00-check
. "${dir}"/functions/01-base
. "${dir}"/functions/01-misc
. "${dir}"/functions/02-desktop
. "${dir}"/functions/03-network
. "${dir}"/functions/03-packages
. "${dir}"/functions/04-themes
. "${dir}"/functions/05-personal


#
# Define main select wrapper
#

function main {
  show_question "Select an option:"
  show_info "Main (Hit ENTER to see options again.)"
  local options=(
    "Quit"
    "Autopilot"
    "Base"
    "Miscellaneous"
    "Desktop environment"
    "Network tools"
    "Applications"
    "Themes"
    "Personalization")
  select option in "${options[@]}"; do
    case "${option}" in
      "Quit")
        show_success "I hope this was as fun for you as it was for me."
        break
        ;;
      "Autopilot")
        local response
        response=$(ask_question "Let this script install everything? (y/N)")
        if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
          # Install base packages
          install_base
          purge_packages
          install_firmware
          enable_contrib_repos
          enable_nonfree_repos
          enable_nonfree-firmware_repos
          update_packages
          enable_sudo_insults
          disable_beep

          # Install miscellaneous extras
          install_zsh
          install_selinux
          install_utils
          # install_laptop

          # Install a desktop environment
          # install_gnome
          install_cinnamon
          # install_kde

          # Set up network configuration
          install_network
          install_firewall
          # install_tor
          # use_onion_repos

          # Install useful packages
          install_3d_accel
          # install_android
          install_apps
          # install_apps_kde
          install_codecs
          install_dev
          install_extra
          # install_extra_kde
          # install_games
          # install_kvm
          # install_kvm_guest
          install_messaging
          # install_mingw
          install_music
          install_pipewire
          install_printing
          install_texlive
          # install_torbrowser
          install_vim
          # install_neovim
          # install_virtualbox
          # install_virtualbox_guest
          # install_wine

          # Install themes
          install_theme_deps_gtk
          # install_theme_deps_kde
          install_arc_gtk
          # install_arc_kde
          # install_adapta_gtk
          # install_plata_gtk
          # install_materia_gtk
          # install_materia_kde
          install_fonts
          install_papirus_icons
          install_colorific_themes
          install_timed_backgrounds
          set_qtcompat

          # Add my personal settings
          set_system_font
          set_icon_theme
          set_gtk_theme
          # set_plasma_theme
          set_lightdm_theme
          # set_gdm_theme
          # set_sddm_theme
          set_dark_gtk
          # set_bash_shell
          set_zsh_shell
          import_cinnamon_dconf
          # import_gnome_dconf
          # import_kde_settings
          import_apps_dconf
          import_terminal_dconf
          enable_autologin
          # invert_brightness
          # enable_intel_iommu
          # disable_pulseaudio_suspend
          disable_11n
          install_scripts

          show_success "Everything installed."
        fi

        show_info "Main (Hit ENTER to see options again.)"
        ;;
      "Base")
        01-base
        show_info "Main (Hit ENTER to see options again.)"
        ;;
      "Miscellaneous")
        01-misc
        show_info "Main (Hit ENTER to see options again.)"
        ;;
      "Desktop environment")
        02-desktop
        show_info "Main (Hit ENTER to see options again.)"
        ;;
      "Network tools")
        03-network
        show_info "Main (Hit ENTER to see options again.)"
        ;;
      "Applications")
        03-packages
        show_info "Main (Hit ENTER to see options again.)"
        ;;
      "Themes")
        04-themes
        show_info "Main (Hit ENTER to see options again.)"
        ;;
      "Personalization")
        05-personal
        show_info "Main (Hit ENTER to see options again.)"
        ;;
      *)
        show_warning "Invalid option."
        ;;
    esac
  done
}


#
# Check if dependencies are installed and if network is working
#

check_user
install_sudo
check_network
check_debian_release
install_post_dependencies


#
# GO!!!
#

main
