#!/bin/bash

# SPDX-FileCopyrightText: 2017 - 2024 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -eu

if [[ $(/usr/bin/bootctl is-installed) = "yes" ]]; then
  EFI_DEST_PATH="$(/usr/bin/bootctl -p)"
elif [ -d /boot/efi ]; then
  EFI_DEST_PATH=/boot/efi
else
  exit
fi

echo "Copying kernel and initrd-${1} to EFI System Partition"
cp -af "${2}" "${EFI_DEST_PATH}"
