#!/bin/bash
set -eu

# Debian (post-)install scripts
# Copyright (C) 2024
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

function make_single_file {
  local contents
  local mode="${1}"
  pushd "$(git rev-parse --show-toplevel)" > /dev/null
  contents="$(tar -cz -O -T <(git ls-files --full-name) | base64 -w 0)"
  cat << EOF
#! /bin/bash
set -Eeu
TMP="\$(mktemp -d)"
trap 'rm -rf "\${TMP}"; exit' INT TERM ERR EXIT
cd "\${TMP}"
tar -m -xzf <(base64 -d <<< ${contents})
./${mode}
EOF
  popd > /dev/null
}

MODE="${1:-both}"

case "${MODE}" in
  both)
    for MODE in install postinstall; do
      make_single_file "${MODE}" > debian_"${MODE}"
      chmod +x debian_"${MODE}"
    done
    ;;
  install | postinstall)
    make_single_file "${MODE}" > debian_"${MODE}"
    chmod +x debian_"${MODE}"
    ;;
  *)
    echo "ERROR: ${MODE@Q} not supported. Exiting."
    exit 3
    ;;
esac
