#!/bin/bash
set -eu

# Debian (post-)install scripts
# Copyright (C) 2024
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

function make_install {
  local archive
  local contents=(
    ./functions/00-check
    ./functions/00-install
    ./hooks
    ./install
    ./packages/install.list
    ./sources
    ./utils/genfstab
  )
  pushd "$(git rev-parse --show-toplevel)" > /dev/null
  archive="$(tar -cz -O "${contents[@]}" | base64 -w 0)"
  cat << EOF
#! /bin/bash
set -Eeu
echo "Running unified Debian 'install' script ($(git rev-parse HEAD))."
TMP="\$(mktemp -d)"
trap 'rm -rf "\${TMP}"; exit' INT TERM ERR EXIT
cd "\${TMP}"
tar -m -xzf <(base64 -d <<< ${archive})
./install
EOF
  popd > /dev/null
}

function make_postinstall {
  local archive
  local contents=(
    ./configs
    ./daemons
    ./dconf
    ./dotfiles
    ./functions/00-check
    ./functions/01-base
    ./functions/01-misc
    ./functions/02-desktop
    ./functions/03-network
    ./functions/03-packages
    ./functions/04-themes
    ./functions/05-personal
    ./packages
    ./postinstall
    ./sources
  )
  pushd "$(git rev-parse --show-toplevel)" > /dev/null
  archive="$(tar -cz -O "${contents[@]}" | base64 -w 0)"
  cat << EOF
#! /bin/bash
set -Eeu
echo "Running unified Debian 'postinstall' script ($(git rev-parse HEAD))."
TMP="\$(mktemp -d)"
trap 'rm -rf "\${TMP}"; exit' INT TERM ERR EXIT
cd "\${TMP}"
tar -m -xzf <(base64 -d <<< ${archive})
./postinstall
EOF
  popd > /dev/null
}

MODE="${1:-both}"

case "${MODE}" in
  both)
    for MODE in install postinstall; do
      make_"${MODE}" > debian_"${MODE}"
      chmod +x debian_"${MODE}"
    done
    ;;
  install | postinstall)
    make_"${MODE}" > debian_"${MODE}"
    chmod +x debian_"${MODE}"
    ;;
  *)
    echo "ERROR: ${MODE@Q} not supported. Exiting."
    exit 3
    ;;
esac
