# env:
#   TERM: xterm-256color

scrolling:
  history: 2000
  multiplier: 5
  faux_multiplier: 5

shell:
  program: /bin/zsh
  args:
    - --login

font:
  normal:
    family: JamboMono Nerd Font
    style: Regular

  bold:
    family: JamboMono Nerd Font
    style: Bold

  italic:
    family: JamboMono Nerd Font
    style: Italic

  bold_italic:
    family: JamboMono Nerd Font
    style: Bold Italic

  size: 9.4

key_bindings:
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }

hints:
  enabled:
   - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
             [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
     command: xdg-open
     post_processing: true
     mouse:
       enabled: false
       mods: None

import:
  - ~/.config/alacritty/nightfox.yml
